version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5000"  # Map port 3000 on the host to port 5000 in the container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    environment:
      - FLASK_ENV=development
